---
- hosts: all
  connection: local
  tasks:
    - name: "Create a VM from a template"
      vmware_guest:
        port: 443
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        folder: /testvms
        name: testvm_2
        state: poweredon
        template: Centos7Template
        datacenter: netappTest
        datastore: DATA2
        disk:
          - size_gb: 40
            type: thin
            datastore: DATA2
        hardware:
          memory_mb: 512
          num_cpus: 2
          num_cpu_cores_per_socket: 1
          scsi: paravirtual
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: False
        networks:
          - name: Vlan77
      delegate_to: localhost
      register: deploy
